# Generated by Django 4.0.3 on 2022-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_cart_id_cart_uuid_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
