# Generated by Django 4.0.3 on 2022-04-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_uuid_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
